export const aiModulesData = [
  {
    id: 'ai-basics',
    title: 'AI va Neyron Tarmoqlar Asoslari',
    description: 'Sun\'iy intellektning kelib chiqishi, neyron tarmoqlarning ishlash mexanizmi hamda ma\'lumotlarni matnlash va tahlil qilish prinsiplari.',
    level: 'Boshlang\'ich',
    duration: '4 hafta',
    moduleCount: '12 ta dars',
    icon: 'cpu',
    category: 'AI Fundamentals',
  },
  {
    id: 'machine-learning',
    title: 'Machine Learning & Data Science',
    description: 'Nazoratli va nazoratsiz ta\'lim (Supervised/Unsupervised Learning), regressiya, klasterlash hamda scikit-learn kutubxonasi.',
    level: 'O\'rta',
    duration: '6 hafta',
    moduleCount: '16 ta dars',
    icon: 'network',
    category: 'ML',
  },
  {
    id: 'generative-ai',
    title: 'Generativ AI va Yirik Til Modellari (LLM)',
    description: 'ChatGPT, Claude, Gemini va Midjourney modellarining ishlash arxitekturasi, Transformer mexanizmi hamda API integratsiyasi.',
    level: 'O\'rta',
    duration: '5 hafta',
    moduleCount: '14 ta dars',
    icon: 'sparkles',
    category: 'Generative AI',
  },
  {
    id: 'prompt-engineering',
    title: 'Prompt Engineering va Neyron Metodlar',
    description: 'Few-shot prompting, Chain-of-Thought, System Prompting hamda AI modellaridan maksimal sifatli natija olish san\'ati.',
    level: 'Boshlang\'ich',
    duration: '3 hafta',
    moduleCount: '10 ta dars',
    icon: 'terminal',
    category: 'Prompting',
  },
  {
    id: 'computer-vision',
    title: 'Computer Vision va Tasvir Tahlili',
    description: 'OpenCV va TensorFlow orqali tasvirlarni tanish, obyektlarni aniqlash hamda yuz va shakllarni skanerlash algoritmlari.',
    level: 'Yuqori',
    duration: '6 hafta',
    moduleCount: '18 ta dars',
    icon: 'eye',
    category: 'Computer Vision',
  },
  {
    id: 'ai-ethics',
    title: 'AI Etikasi, Xavfsizlik va Mualliflik',
    description: 'AI modellaridagi noaniqliklar, ma\'lumotlar maxfiyligi, intellektual mulk va Responsible AI mezonlari.',
    level: 'Barcha daraja',
    duration: '2 hafta',
    moduleCount: '8 ta dars',
    icon: 'shield-check',
    category: 'Ethics',
  },
];
