export const coursesData = [
  {
    id: 'ai-basics',
    title: 'Sun\'iy Intellekt Asoslari',
    description: 'Neyron tarmoqlar, ma\'lumotlar tahlili va AI texnologiyalarining ishlash prinsiplari.',
    level: 'Boshlang\'ich',
    duration: '4 hafta',
    icon: 'cpu',
    category: 'AI Academy',
    lessonsCount: 12,
    badge: 'Ommabop',
  },
  {
    id: 'generative-ai',
    title: 'Generativ AI va LLM',
    description: 'Yirik til modellari, ChatGPT, Midjourney va tekst/tasvir yaratuvchi neyron tarmoqlar.',
    level: 'O\'rta',
    duration: '6 hafta',
    icon: 'sparkles',
    category: 'Generativ AI',
    lessonsCount: 16,
    badge: 'Yangi',
  },
  {
    id: 'prompt-engineering',
    title: 'Prompt Engineering',
    description: 'AI modellariga to\'g\'ri va aniq ko\'rsatmalar berish hamda professional natijalar olish.',
    level: 'Boshlang\'ich',
    duration: '3 hafta',
    icon: 'terminal',
    category: 'Amaliy AI',
    lessonsCount: 10,
    badge: 'Amaliy',
  },
  {
    id: 'ai-ethics',
    title: 'AI Etikasi va Kiberxavfsizlik',
    description: 'Sun\'iy intellekt xavfsizligi, mas\'uliyatli AI, mualliflik huquqlari va ma\'lumotlar himoyasi.',
    level: 'Barcha daraja',
    duration: '2 hafta',
    icon: 'shield-check',
    category: 'Xavfsizlik',
    lessonsCount: 8,
    badge: 'Tavsiya etiladi',
  },
  {
    id: 'python-programming',
    title: 'Python bilan Dasturlash',
    description: 'AI va Data Science sohasi uchun zarur bo\'lgan Python sintaksisi va kutubxonalar.',
    level: 'Boshlang\'ich',
    duration: '8 hafta',
    icon: 'code-2',
    category: 'Dasturlash',
    lessonsCount: 24,
    badge: 'Bazaviy',
  },
  {
    id: 'web-dev-ai',
    title: 'Web Dasturlash va AI Integratsiya',
    description: 'Zamonaviy web ilovalarga AI API larini ulash hamda interaktiv platformalar yaratish.',
    level: 'Yuqori',
    duration: '6 hafta',
    icon: 'globe',
    category: 'Web Dev',
    lessonsCount: 18,
    badge: 'Intensiv',
  },
];
