export const factsData = [
  {
    id: 1,
    title: 'Neyron tarmoqlar va Inson miyasi',
    fact: 'Sun\'iy neyron tarmoqlari inson miyasidagi 86 milliard neyronlarning o\'zaro bog\'liqlik prinsipiga asoslanib yaratilgan. Ular ma\'lumotlarni qatlamma-qatlam qayta ishlaydi.',
    category: 'AI',
    readTime: '1 daqiqa',
  },
  {
    id: 2,
    title: 'Prompt Engineering mutaxassisligi',
    fact: 'Generativ AI modellari rivojlanishi natijasida "Prompt Engineering" — AI modellariga to\'g\'ri ko\'rsatma berish va optimal natija olish san\'ati alohida kasbga aylandi.',
    category: 'AI',
    readTime: '1 daqiqa',
  },
  {
    id: 3,
    title: 'Transformer Arxitekturasi (2017)',
    fact: 'Zamonaviy barcha yirik til modellari (LLM) 2017-yilda Google tadqiqotchilari tomonidan taqdim etilgan "Attention Is All You Need" maqolasidagi Transformer arxitekturasiga tayanadi.',
    category: 'Programming',
    readTime: '1.5 daqiqa',
  },
  {
    id: 4,
    title: 'Tyuiring Testi (Turing Test)',
    fact: '1950-yilda Alan Tyuiring mashinaning fikrlash qobiliyatini baholash uchun "Imitation Game" (Tyuiring testi) tushunchasini taklif etgan. Bu sun\'iy intellekt tarixidagi burilish nuqtasi hisoblanadi.',
    category: 'Science',
    readTime: '1 daqiqa',
  },
  {
    id: 5,
    title: 'Kompyuterda Ko\'rish (Computer Vision)',
    fact: 'Kompyuterda ko\'rish texnologiyasi tibbiyotda rentgen va MRT tasvirlaridagi shishlarni inson ko\'zidan ko\'ra 98% aniqlik bilan ertaroq aniqlashga yordam bermoqda.',
    category: 'Science',
    readTime: '1.5 daqiqa',
  },
  {
    id: 6,
    title: 'Robototexnika va Sun\'iy Intellekt',
    fact: 'Zamonaviy avtonom robotlar atrof-muhitni tanish va to\'siqlarni aylanib o\'tish uchun sekundiga 30 marta SLAM (Simultaneous Localization and Mapping) algoritmlarini ishlatadi.',
    category: 'Robotics',
    readTime: '1 daqiqa',
  },
  {
    id: 7,
    title: 'Kiberxavfsizlikda AI Tahlili',
    fact: 'Zamonaviy antivirus va kiberhimoya tizimlari sekundiga millionlab tarmoq so\'rovlarini tahlil qilib, ilgari uchramagan yangi virus (Zero-Day) hamlalarini AI yordamida aniqlaydi.',
    category: 'Cybersecurity',
    readTime: '1 daqiqa',
  },
  {
    id: 8,
    title: 'Koinot Tadqiqotlarida AI',
    fact: 'NASA va ESA olimlari Jeyms Uebb kosmik teleskopi to\'plagan petabaytlab ma\'lumotlarni tahlil qilish va yangi ekzoplanetalarni kashf etish uchun neyron tarmoqlardan foydalanadi.',
    category: 'Space',
    readTime: '1.5 daqiqa',
  },
  {
    id: 9,
    title: 'Kvant Kompyuterlari va AI',
    fact: 'Kvant kompyuterlari (Quantum Computing) neyron tarmoqlarni o\'rgatish vaqtini yillardan bir necha sekundgacha qisqartirish salohiyatiga ega.',
    category: 'Science',
    readTime: '1 daqiqa',
  },
  {
    id: 10,
    title: 'Kvadrokopterlar va Swarm Intelligence',
    fact: 'To\'da intellekti (Swarm Intelligence) algoritmlari minglab dronlarning markaziy boshqaruvsiz bir-biri bilan to\'qnashmay guruh bo\'lib uchishini ta\'minlaydi.',
    category: 'Robotics',
    readTime: '1 daqiqa',
  },
  {
    id: 11,
    title: 'Python Tilining Mashhurligi',
    fact: 'Python sodda sintaksisi hamda PyTorch, TensorFlow, Pandas va Scikit-Learn kabi boy kutubxona ekotizimi sababli AI sohasining 1-raqamli tiliga aylandi.',
    category: 'Programming',
    readTime: '1 daqiqa',
  },
  {
    id: 12,
    title: 'Genetika va AlfaFold',
    fact: 'DeepMind kompaniyasining AlphaFold sun\'iy intellekt modeli biologiyadagi 50 yillik muammo — oqsillar tuzilishini (protein folding) 3D shaklda aniqlashni hal etdi.',
    category: 'Science',
    readTime: '1.5 daqiqa',
  },
  {
    id: 13,
    title: 'Kosmik Chaqinlar va AI Tahlili',
    fact: 'Marsdagi Perseverance roveri o\'zining bortidagi AI chipi yordamida tog\' jinslarini mustaqil tanlaydi va o'zining harakat yo'nalishini inson boshqaruvisiz rejalashtiradi.',
    category: 'Space',
    readTime: '1 daqiqa',
  },
  {
    id: 14,
    title: 'Zero-Trust Kiberxavfsizlik',
    fact: 'Zero-Trust ("Hech kimga ishonma") tamoyili har bir tarmoq so'rovini foydalanuvchining joylashuvi va qurilmasidan qat'i nazar qayta autentifikatsiya qilishni talab qiladi.',
    category: 'Cybersecurity',
    readTime: '1 daqiqa',
  },
  {
    id: 15,
    title: 'Avtonom Haydash va LiDaR',
    fact: 'Haydovchisiz avtomobillar atrof-muhitning uch o\'lchamli xaritasini hosil qilish uchun soniyasiga millionlab lazer nurlarini otuvchi LiDaR sensorlaridan foydalanadi.',
    category: 'Robotics',
    readTime: '1 daqiqa',
  },
  {
    id: 16,
    title: 'Synthetic Data (Sintetik Ma\'lumotlar)',
    fact: 'Neyron tarmoqlarni o\'rgatish uchun inson ma\'lumotlari yetishmaganda, AI modellari o'zi uchun sintetik (sun'iy generatsiya qilingan) ma'lumotlar to'plamini yaratadi.',
    category: 'AI',
    readTime: '1 daqiqa',
  },
  {
    id: 17,
    title: 'Dasturchilar va AI Copilot',
    fact: 'Tadqiqotlarga ko\'ra, AI kod yordamchilaridan foydalanuvchi dasturchilar topshiriqlarni 55% tezroq bajaradi va rutin kod yozish vaqtini iqtisod qiladi.',
    category: 'Programming',
    readTime: '1 daqiqa',
  },
  {
    id: 18,
    title: 'Quyosh Shodligi va Kosmik Ob-havo AI',
    fact: 'Quyoshdagi chaqnashlar va geomagnit bo\'ronlarni 24 soat oldin bashorat qilish uchun Quyosh teleskopi tasvirlari neyron tarmoqlar orqali uzluksiz tahlil qilinadi.',
    category: 'Space',
    readTime: '1 daqiqa',
  },
  {
    id: 19,
    title: 'Biometrik Xavfsizlik',
    fact: 'Yuz va ko\'z qorachig'i bo'yicha biometrik autentifikatsiya modellari tasvir soxtalashtirishini (deepfake) aniqlash uchun terining mikro-tebranishlarini o'lchaydi.',
    category: 'Cybersecurity',
    readTime: '1 daqiqa',
  },
  {
    id: 20,
    title: 'Responsible AI va Adolat',
    fact: 'AI modellari odamlarga nisbatan adolatli bo\'lishi uchun o\'quv ma'lumotlaridagi ijtimoiy yonbosishlarni (bias) tozalash bo'yicha maxsus audit algoritmlari qo'llaniladi.',
    category: 'AI',
    readTime: '1 daqiqa',
  },
];
