export const mediaItemsData = [
  {
    id: 'media-1',
    type: 'video',
    category: 'Darslar',
    title: 'Sun\'iy Intellekt va Neyron Tarmoqlar Asoslari',
    duration: '45:00 min',
    gradient: 'linear-gradient(135deg, rgba(0, 240, 255, 0.2) 0%, rgba(59, 130, 246, 0.3) 100%)',
    description: 'Neyron tarmoqlarning matematik modeli va kompyuterda ma\'lumotlarni tahlil qilish darsligi.',
  },
  {
    id: 'media-2',
    type: 'video',
    category: 'Video',
    title: 'Generativ AI va Prompting Master-Klass',
    duration: '28:15 min',
    gradient: 'linear-gradient(135deg, rgba(139, 92, 246, 0.2) 0%, rgba(59, 130, 246, 0.3) 100%)',
    description: 'Yirik til modellari bilan professional ishlash va samarali promptlar tuzish.',
  },
  {
    id: 'media-3',
    type: 'foto',
    category: 'Foto',
    title: 'Akademiya AI Laboratoriyasi va O\'quv Xonalari',
    duration: '12 ta foto',
    gradient: 'linear-gradient(135deg, rgba(16, 185, 129, 0.2) 0%, rgba(0, 240, 255, 0.3) 100%)',
    description: 'Zamonaviy kompyuter va AI laboratoriyasining ichki sharoitlari va infratuzilmasi.',
  },
  {
    id: 'media-4',
    type: 'video',
    category: 'Tadbirlar',
    title: 'UZXIAtreatr Hackathon 2026 G\'oliblar Taqdimoti',
    duration: '18:40 min',
    gradient: 'linear-gradient(135deg, rgba(245, 158, 11, 0.2) 0%, rgba(139, 92, 246, 0.3) 100%)',
    description: 'Hackathon finalistlarining taqdimotlari va g\'oliblarni taqdirlash marosimi.',
  },
  {
    id: 'media-5',
    type: 'foto',
    category: 'Tadbirlar',
    title: 'Xalqaro AI Konferensiyasi Foto Jamlanmasi',
    duration: '24 ta foto',
    gradient: 'linear-gradient(135deg, rgba(244, 63, 94, 0.2) 0%, rgba(59, 130, 246, 0.3) 100%)',
    description: 'Mehmon ma\'ruzachilar va talabalar uchrashuvidan yorqin lavhalar.',
  },
  {
    id: 'media-6',
    type: 'video',
    category: 'Darslar',
    title: 'Python bilan Data Science Darsligi',
    duration: '32:10 min',
    gradient: 'linear-gradient(135deg, rgba(0, 240, 255, 0.25) 0%, rgba(16, 185, 129, 0.2) 100%)',
    description: 'Pandas va Matplotlib yordamida ma\'lumotlarni vizuallashtirish amaliyoti.',
  },
];
