export const quizQuestionsData = [
  // CATEGORY: AI
  {
    id: 1,
    category: 'AI',
    difficulty: 'Boshlang\'ich',
    question: 'Sun\'iy intellektda "LLM" abbreviasiyasi nimani anglatadi?',
    options: ['Large Language Model', 'Logic Learning Machine', 'Linear Local Matrix', 'Linked Level Mechanism'],
    correctIndex: 0,
    explanation: 'LLM — Large Language Model (Yirik Til Modeli) bo\'lib, matnlarni tushunish va generatsiya qilish uchun milliardlab parametrlar bilan o\'rgatilgan neyron tarmoqdir.',
  },
  {
    id: 2,
    category: 'AI',
    difficulty: 'O\'rta',
    question: 'ChatGPT va Claude kabi zamonaviy modellarning asosi bo\'lgan arxitektura qaysi?',
    options: ['Convolutional Neural Network', 'Recurrent Neural Network', 'Transformer Arxitekturasi', 'Decision Trees'],
    correctIndex: 2,
    explanation: 'Transformer arxitekturasi 2017-yilda taklif etilgan va barcha zamonaviy yirik til modellarining poydevori hisoblanadi.',
  },
  {
    id: 3,
    category: 'AI',
    difficulty: 'Yuqori',
    question: 'Neyron tarmoqni o\'rgatishda og\'ishlarni (weights) tuzatuvchi algoritm nima deyiladi?',
    options: ['Backpropagation', 'Gradient Boost', 'K-Means', 'A* Search'],
    correctIndex: 0,
    explanation: 'Backpropagation (Xatolikni orqaga tarqatish) algoritmi neyron tarmoq og\'ishlarini optimallashtirish uchun xatolik gradientini hisoblaydi.',
  },
  {
    id: 4,
    category: 'AI',
    difficulty: 'Boshlang\'ich',
    question: 'AI modeliga ko\'rsatma va topshiriq berish jarayoni nima deyiladi?',
    options: ['Prompt Engineering', 'Database Indexing', 'Syntax Parsing', 'Compiling'],
    correctIndex: 0,
    explanation: 'Prompt Engineering — bu AI modellariga to\'g\'ri ko\'rsatma berib, ulardan eng aniq va sifatli natijani olish usulidir.',
  },
  {
    id: 5,
    category: 'AI',
    difficulty: 'O\'rta',
    question: 'AI modelining mavjud bo\'lmagan noto\'g\'ri ma\'lumotni ishonch bilan taqdim etishi holati nima deyiladi?',
    options: ['Overfitting', 'Hallucination (Gallyutsinatsiya)', 'Underfitting', 'Data Drift'],
    correctIndex: 1,
    explanation: 'AI gallyutsinatsiyasi — neyron tarmoq mantiqsiz yoki soxta ma\'lumotni xuddi haqiqatdek generatsiya qilishi holatidir.',
  },

  // CATEGORY: Programming
  {
    id: 6,
    category: 'Programming',
    difficulty: 'Boshlang\'ich',
    question: 'Python dasturlash tilida ro\'yxat (list) qaysi qavs bilan e\'lon qilinadi?',
    options: ['[ ] to\'rtburchak qavs', '{ } jingalak qavs', '( ) yumaloq qavs', '< > burchakli qavs'],
    correctIndex: 0,
    explanation: 'Python tilida ro\'yxat [ ] to\'rtburchak qavslar orqali yaratiladi.',
  },
  {
    id: 7,
    category: 'Programming',
    difficulty: 'O\'rta',
    question: 'O\'z-o\'zini chaqiruvchi dasturlash funksiyalari nima deyiladi?',
    options: ['Iteration', 'Recursion (Rekursiya)', 'Abstraction', 'Polymorphism'],
    correctIndex: 1,
    explanation: 'Rekursiya — bu funksiya o\'z tanasi ichida o\'zini qayta chaqirish mexanizmidir.',
  },
  {
    id: 8,
    category: 'Programming',
    difficulty: 'Yuqori',
    question: 'Ob\'ektga yo\'naltirilgan dasturlashda (OOP) vorislik tushunchasi nimani anglatadi?',
    options: ['Inheritance', 'Encapsulation', 'Polymorphism', 'Abstraction'],
    correctIndex: 0,
    explanation: 'Inheritance (Vorislik) yangi sinfning mavjud ota sinf xususiyatlari va metodlarini meros qilib olishidir.',
  },
  {
    id: 9,
    category: 'Programming',
    difficulty: 'Boshlang\'ich',
    question: 'Web-sahifa strukturasini belgilovchi asosiy belgilash tili qaysi?',
    options: ['HTML', 'CSS', 'JavaScript', 'SQL'],
    correctIndex: 0,
    explanation: 'HTML (HyperText Markup Language) veb-sahifaning asosiy karkas va strukturasini hosil qiladi.',
  },
  {
    id: 10,
    category: 'Programming',
    difficulty: 'O\'rta',
    question: 'JavaScript tilida o\'zgaruvchi e\'lon qilish uchun qaysi kalit so\'zlar ishlatiladi?',
    options: ['let, const, var', 'int, float, char', 'define, val', 'make, set'],
    correctIndex: 0,
    explanation: 'Zamonaviy JavaScript tilida let, const hamda eskiroq var o\'zgaruvchilarni e\'lon qilishda qo\'llaniladi.',
  },

  // CATEGORY: Cybersecurity
  {
    id: 11,
    category: 'Cybersecurity',
    difficulty: 'Boshlang\'ich',
    question: 'Soxta xabar yoki veb-sayt orqali shaxsiy parollarni o\'g\'irlash hamlasi nima deyiladi?',
    options: ['Phishing (Fishing)', 'DDoS', 'SQL Injection', 'Ransomware'],
    correctIndex: 0,
    explanation: 'Fishing — foydalanuvchilarni aldab, soxta sahifa orqali maxfiy ma\'lumotlarini qo\'lga kiritish kiber-hujumidir.',
  },
  {
    id: 12,
    category: 'Cybersecurity',
    difficulty: 'O\'rta',
    question: 'Server xotirasini soxta so\'rovlar bilan to\'ldirib, ishdan chiqarish hamlasi nima deyiladi?',
    options: ['DDoS (Distributed Denial of Service)', 'Brute Force', 'Man-in-the-Middle', 'Cross-Site Scripting'],
    correctIndex: 0,
    explanation: 'DDoS hujumi serverga bir vaqtda millionlab soxta so\'rovlar yuborib, uning ishlashini to\'xtatib qo\'yadi.',
  },
  {
    id: 13,
    category: 'Cybersecurity',
    difficulty: 'Yuqori',
    question: 'Foydalanuvchi ma\'lumotlarini shifrlab, kalit uchun to'lov talab qiluvchi zararli dastur nima deyiladi?',
    options: ['Ransomware (Tovlamachi dastur)', 'Adware', 'Spyware', 'Keylogger'],
    correctIndex: 0,
    explanation: 'Ransomware fayllarni shifrlaydi va ularni ochish uchun to'lov talab etuvchi kiber-tahdid turidir.',
  },
  {
    id: 14,
    category: 'Cybersecurity',
    difficulty: 'Boshlang\'ich',
    question: 'Ikki bosqichli autentifikatsiya (2FA) nima uchun kerak?',
    options: ['Paroldan tashqari qo\'shimcha tasdiqlash kodi orqali xavfsizlikni oshirish', 'Internet tezligini oshirish', 'Fayl hajmini kichraytirish', 'Sayt dizaynini o\'zgartirish'],
    correctIndex: 0,
    explanation: '2FA akkauntga kirishda paroldan tashqari SMS yoki ilova kodi orqali ikkinchi himoya qatlamini yaratadi.',
  },

  // CATEGORY: Technology
  {
    id: 15,
    category: 'Technology',
    difficulty: 'Boshlang\'ich',
    question: 'Inson va mashina muloqotini baholovchi mashhur test muallifi kim?',
    options: ['Alan Turing', 'Bill Gates', 'Steve Jobs', 'Elon Musk'],
    correctIndex: 0,
    explanation: 'Alan Tyuiring 1950-yilda mashinalarning intellektual salohiyatini sinovchi test konsepsiyasini taklif etgan.',
  },
  {
    id: 16,
    category: 'Technology',
    difficulty: 'O\'rta',
    question: 'Bulutli texnologiyalarda (Cloud Computing) "AWS" qaysi kompaniyaga tegishli?',
    options: ['Amazon Web Services', 'Apple Web System', 'Advanced Web Solution', 'Android World Software'],
    correctIndex: 0,
    explanation: 'AWS (Amazon Web Services) dunyodagi eng yirik bulutli infratuzilma provayderlaridan biridir.',
  },
  {
    id: 17,
    category: 'Technology',
    difficulty: 'Yuqori',
    question: 'Kvant kompyuterlarida ma\'lumotlarning eng kichik birligi nima deyiladi?',
    options: ['Qubit (Kubit)', 'Bit', 'Byte', 'Pixel'],
    correctIndex: 0,
    explanation: 'Qubit — kvant superpozitsiyasi tufayli bir vaqtning o\'zida ham 0, ham 1 holatida bo\'la oladigan kvant biti.',
  },
  {
    id: 18,
    category: 'Technology',
    difficulty: 'Boshlang\'ich',
    question: 'Ochiq manbali (Open Source) kodlarni saqlash va hamkorlikda ishlash platformasi qaysi?',
    options: ['GitHub', 'Photoshop', 'Excel', 'Figma'],
    correctIndex: 0,
    explanation: 'GitHub dasturchilar uchun versiyalarni boshqarish (Git) va ochiq loyihalarda hamkorlik qilish tarmog\'idir.',
  },
];
