export const resourcesData = [
  {
    id: 'res-books',
    title: 'Kitoblar va Qo\'llanmalar',
    category: '📚 Kitoblar',
    description: 'AI, Python, algoritm va kiberxavfsizlik bo\'yicha elektron o\'quv adabiyotlar to\'plami.',
    icon: 'book-open',
    linkText: 'Kutubxonani ochish',
  },
  {
    id: 'res-dev',
    title: 'Dasturlash Muhitlari',
    category: '💻 Dasturlash',
    description: 'VS Code, PyCharm, Jupyter Notebook sozlalamalari hamda tezkor kod yozish qo\'llanmalari.',
    icon: 'code-2',
    linkText: 'Kodni sozlash',
  },
  {
    id: 'res-ai-tools',
    title: 'AI Vositalari Katalogi',
    category: '🤖 AI Tools',
    description: 'Tadqiqot, matn yaratish va tasvirlar bilan ishlash uchun eng samarali bepul AI vositalari.',
    icon: 'cpu',
    linkText: 'Vositalarni ko\'rish',
  },
  {
    id: 'res-useful-sites',
    title: 'Foydali Ta\'lim Platformalari',
    category: '🌐 Foydali saytlar',
    description: 'GitHub, Kaggle, LeetCode va Xalqaro o\'quv platformalarining sara havolalari.',
    icon: 'globe',
    linkText: 'Saytlarga o\'tish',
  },
  {
    id: 'res-english',
    title: 'Texnik Ingliz Tili',
    category: '🇬🇧 Ingliz tili',
    description: 'Dasturchilar va AI mutaxassislari uchun maxsus lug\'atlar va terminologiya to\'plami.',
    icon: 'languages',
    linkText: 'Lug\'atni o\'rganish',
  },
  {
    id: 'res-cyber',
    title: 'Kiberxavfsizlik Qo\'llanmasi',
    category: '🔐 Kiberxavfsizlik',
    description: 'Shaxsiy ma\'lumotlar daxlsizligi, parollar xavfsizligi va fishing hamlalaridan himoyalanish.',
    icon: 'shield-alert',
    linkText: 'Xavfsizlik qoidalari',
  },
];
